import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'

const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const browser = await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE })
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
const errors = []
await context.route('**/src/hooks/useFirebaseAuth.js*', (route) => route.fulfill({
  contentType: 'application/javascript',
  body: 'export const OWNER_UID="test-owner"; export default function useFirebaseAuth(){return {user:{uid:OWNER_UID},loading:false,login(){},logout(){}}}',
}))
await context.route('**/src/lib/firebase.js*', (route) => route.fulfill({
  contentType: 'application/javascript',
  body: 'export const firebaseReady=false; export const auth=null; export const database=null;',
}))
await context.addInitScript(() => {
  Object.defineProperty(crypto, 'randomUUID', { value: undefined, configurable: true })
})
const page = await context.newPage()
page.on('pageerror', (error) => errors.push(error.message))
const base = process.env.TEST_URL || 'http://127.0.0.1:5173'
await mkdir('artifacts', { recursive: true })
try {
  await page.goto(base)
  await page.locator('.edit-tags-button').click()
  await page.getByRole('button', { name: '編輯標籤', exact: true }).click()
  const tagOrder = () => page.locator('.tag-editor-item input').evaluateAll((inputs) => inputs.map((input) => input.value))
  const initialOrder = await tagOrder()
  const firstHandle = await page.locator('.tag-drag-handle').first().boundingBox()
  const thirdRow = await page.locator('.tag-editor-item').nth(2).boundingBox()
  await page.mouse.move(firstHandle.x + firstHandle.width / 2, firstHandle.y + firstHandle.height / 2)
  await page.mouse.down()
  await page.mouse.move(firstHandle.x + firstHandle.width / 2, thirdRow.y + thirdRow.height - 2, { steps: 8 })
  await page.locator('.tag-drop-after').waitFor()
  await page.mouse.up()
  const reordered = [initialOrder[1], initialOrder[2], initialOrder[0], ...initialOrder.slice(3)]
  assert.deepEqual(await tagOrder(), reordered)
  await page.getByRole('button', { name: '儲存標籤', exact: true }).click()
  await page.locator('.action-modal button').last().click()
  await page.reload()
  const filterOrder = await page.locator('.tag-pill').allTextContents()
  assert.deepEqual(filterOrder.slice(1).map((label) => label.replace(/^#\s*/, '').trim()), reordered)
  await page.locator('.edit-tags-button').click()
  await page.getByRole('button', { name: '編輯標籤', exact: true }).click()
  await page.locator('.tag-drag-handle').first().focus()
  await page.keyboard.press('End')
  assert.equal((await tagOrder()).at(-1), reordered[0])
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '編輯標籤', exact: true }).click()
  assert.deepEqual(await tagOrder(), reordered)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.locator('.tag-editor-item').first().scrollIntoViewIfNeeded()
  const touchHandle = await page.locator('.tag-drag-handle').first().boundingBox()
  const touchTarget = await page.locator('.tag-editor-item').nth(2).boundingBox()
  const cdp = await context.newCDPSession(page)
  await cdp.send('Emulation.setTouchEmulationEnabled', { enabled: true })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: touchHandle.x + 16, y: touchHandle.y + 20 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: touchHandle.x + 16, y: touchTarget.y + touchTarget.height - 2 }] })
  await page.locator('.tag-drop-after').waitFor()
  await page.screenshot({ path: 'artifacts/tag-drag-mobile.png' })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  assert.deepEqual(await tagOrder(), [reordered[1], reordered[2], reordered[0], ...reordered.slice(3)])
  await cdp.send('Emulation.setTouchEmulationEnabled', { enabled: false })
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.reload()
  for (const [label, path] of [['全部收藏', '/'], ['BGM', '/bgm'], ['MUSIC', '/music'], ['作業用', '/Productivity']]) {
    await page.getByRole('link', { name: new RegExp(label) }).last().click()
    assert.equal(new URL(page.url()).pathname, path)
    await page.locator('.edit-tags-button').click()
    await page.getByRole('button', { name: '編輯標籤', exact: true }).click()
    await page.getByRole('button', { name: '新增', exact: true }).click()
    await page.getByRole('alert').filter({ hasText: '請輸入新標籤名稱' }).waitFor()
    await page.getByRole('textbox', { name: '新標籤名稱', exact: true }).fill(`test-${label}`)
    await page.getByRole('button', { name: '新增', exact: true }).click()
    assert.equal(await page.getByRole('textbox', { name: '新標籤名稱', exact: true }).inputValue(), '')
    await page.getByRole('button', { name: '儲存標籤', exact: true }).click()
    await page.locator('.action-modal button').last().click()
    await page.getByRole('button', { name: `# test-${label}`, exact: true }).waitFor()
    await page.reload()
    await page.getByRole('button', { name: `# test-${label}`, exact: true }).waitFor()
  }
  const savedTags = () => page.evaluate(() => JSON.parse(localStorage.getItem('yozu-music-tags-v1')))
  const beforeSync = await savedTags()
  await page.locator('.edit-tags-button').click()
  await page.getByRole('button', { name: '編輯標籤', exact: true }).click()
  await page.getByRole('radio', { name: '指定分頁', exact: true }).check()
  await page.getByRole('textbox', { name: '新標籤名稱', exact: true }).fill('selected-sync')
  await page.getByRole('button', { name: '新增', exact: true }).click()
  await page.getByRole('alert').filter({ hasText: '請勾選要同步的分頁' }).waitFor()
  await page.getByRole('checkbox', { name: 'BGM', exact: true }).check()
  await page.getByRole('checkbox', { name: '作品', exact: true }).check()
  await page.getByRole('button', { name: '新增', exact: true }).click()
  await page.getByRole('radio', { name: '僅本頁', exact: true }).check()
  await page.getByRole('textbox', { name: '新標籤名稱', exact: true }).fill('local-only')
  await page.getByRole('button', { name: '新增', exact: true }).click()
  await page.getByRole('radio', { name: '全部分頁', exact: true }).check()
  await page.getByRole('textbox', { name: '新標籤名稱', exact: true }).fill('deleted-before-save')
  await page.getByRole('button', { name: '新增', exact: true }).click()
  await page.getByRole('button', { name: '刪除 deleted-before-save', exact: true }).click()
  await page.getByRole('textbox', { name: '新標籤名稱', exact: true }).fill('global-sync')
  assert.deepEqual(await savedTags(), beforeSync)
  await page.screenshot({ path: 'artifacts/tag-sync-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('radio', { name: '指定分頁', exact: true }).check()
  await page.locator('.tag-sync-options').scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'artifacts/tag-sync-mobile.png', fullPage: true })
  assert.equal(await page.locator('.tag-editor').evaluate((el) => el.scrollWidth <= el.clientWidth), true)
  await page.getByRole('radio', { name: '全部分頁', exact: true }).check()
  await page.getByRole('button', { name: '儲存標籤', exact: true }).click()
  await page.locator('.action-modal button').last().click()
  await page.reload()
  const afterSync = await savedTags()
  for (const [section, tags] of Object.entries(afterSync)) {
    assert.equal(tags.some((tag) => tag.label === 'global-sync'), true)
    assert.equal(tags.some((tag) => tag.label === 'selected-sync'), ['作業用', 'BGM', '作品'].includes(section))
    assert.equal(tags.some((tag) => tag.label === 'local-only'), section === '作業用')
    assert.equal(tags.some((tag) => tag.label === 'deleted-before-save'), false)
    assert.deepEqual(tags.slice(0, beforeSync[section].length), beforeSync[section])
  }
  assert.equal(new Set(Object.values(afterSync).map((tags) => tags.find((tag) => tag.label === 'global-sync').id)).size, 1)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.locator('.edit-tags-button').click()
  await page.getByRole('button', { name: '編輯標籤', exact: true }).click()
  await page.getByRole('radio', { name: '全部分頁', exact: true }).check()
  await page.getByRole('textbox', { name: '新標籤名稱', exact: true }).fill('cancelled-sync')
  await page.getByRole('button', { name: '新增', exact: true }).click()
  await page.getByRole('button', { name: '取消', exact: true }).click()
  assert.deepEqual(await savedTags(), afterSync)
  await page.getByRole('link', { name: /^作品/ }).click()
  await page.screenshot({ path: 'artifacts/works-desktop.png', fullPage: true })
  assert.equal(await page.locator('.work-card-body').first().evaluate((el) => getComputedStyle(el).minHeight), '150px')
  await page.locator('.work-card').first().click()
  assert.match(new URL(page.url()).pathname, /^\/works\/view\//)
  await page.locator('.work-page').waitFor()
  assert.equal(await page.locator('.work-modal-backdrop').count(), 0)
  await page.reload()
  await page.locator('.work-page').waitFor()
  await page.locator('.work-page .edit-tags-button').click()
  await page.getByRole('button', { name: '編輯標籤', exact: true }).click()
  await page.getByRole('textbox', { name: '新標籤名稱', exact: true }).fill('work-tag')
  await page.getByRole('textbox', { name: '新標籤名稱', exact: true }).press('Enter')
  await page.getByRole('button', { name: '儲存標籤', exact: true }).click()
  await page.locator('.action-modal button').last().click()
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('yozu-music-tags-v1'))['作品'].some((tag) => tag.label === 'work-tag')), true)
  await page.getByRole('button', { name: '# work-tag', exact: true }).waitFor()
  await page.screenshot({ path: 'artifacts/work-page-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'artifacts/work-page-mobile.png', fullPage: true })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  await page.getByRole('button', { name: '返回作品', exact: true }).click()
  assert.equal(new URL(page.url()).pathname, '/works')
  await page.goBack()
  await page.locator('.work-page').waitFor()
  assert.deepEqual(errors, [])
  console.log('PASS: routes, local/selected/all tag sync, pending input, cancel/delete, UUID fallback, reload, work page, responsive layout')
} finally {
  await browser.close()
}
